django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ed.urls')),
    path('accounts/', include('allauth.urls')),
]

ed/urls.py
from . import views
from django.urls import path

app_name = 'ed'
urlpatterns = [
    path('', views.home, name='home'),
    path('videos/', views.videos, name='video'),
    # Forum
    path('forum/', views.forum_view, name='forum'),
    path('forum/comment/', views.comment_view, name='comment'),
    path('forum/create', views.forum_create, name='create'),
    path('forum/search/', views.search_post, name='message_search'),
    path('forum/filter', views.advfilter, name='advfilter'),
    path('forum/searchworker/', views.searchworker_view, name='searchworker'),
    # Forum End
    path('posts/', views.posts, name='posts'),
    path('contact/', views.contacts, name='contact'),
    # Prole
    path('profile/', views.profile_view, name='profile'),
    path('profile/fa/', views.fa, name='fa'),
    path('profileadd', views.profile_add, name='profile_add'),
    path('notification', views.notification_view, name='notification'),
    path('settings', views.settings_view, name='settings'),
    # Account
    path('login/', views.login_view, name='login_view'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    # Old Site
    path('sale/', views.sale, name='sale'),
    # For Supporter
    path('supporter/', views.supporter, name='supporter'),
    # Help
    path('problems', views.problems, name='problem'),
    # Rickroll
    path('tests', views.rickroll, name='rickroll'),

]

templates/nick/forum/advancedSRC.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>EDGermanFlex / filter</title>
    <link rel="stylesheet" href={% static 'css/nick/holy-cascade.css' %}>
    <link rel="icon" href={% static 'img/nick/logo.png' %}>
    <!--Global light & dark & mobile -->
    <link rel="stylesheet" href="{% static 'css/nick/light/css/global.css' %}">
    <link rel="stylesheet" href="{% static 'css/nick/dark/css/global.css' %}">
    <link rel="stylesheet" href="{% static 'css/nick/mobile/css/global.css' %}">
    <!--End of scss-->
</head>
    <body>

        <center>
            <div id="container">
                <form action="{% url 'ed:message_search' %}">
                <label style="font-size: 24px; padding: 10px; color: rgb(0, 0, 0);"><b>Search by</b></label><br><br><br>
                <label style="float: left; ">Username:</label>
                <input name="user" style="float: right;" type="text" placeholder="username" id="usernameSRC"><br><br>
                <label style="float: left; padding-right: 20px;">Title:</label>
                <input name="title" style="float: right;" type="text" placeholder="title" id="usernameSRC"><br><br>
                <label style="float: left; padding-right: 20px;">Keywords:</label>
                <input name="keywords" style="float: right;" type="text" placeholder="keywords" id="keywordSRC"><br><br>
                <label style="float: left; padding-right: 20px;">Date:</label>
                <input name="date" style="float: left; margin-left: 33px;" type="date" id="dateSRC" style="width: 100px;"><br><br>


                <label style="float: left; padding-right: 20px;">Popularity:</label>
                <select name="popularity" style="float: left;" id='popularityList'>
                    <option value="mostlike">Most liked</option>
                    <option value="lesslike">Least liked</option>
                </select><br><br>

                <input type="submit" style="float: right;"><br>
                </form>
            </div>
        </center>

    </body>
</html>

templates/nick/forum/comment.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>
            EDgermanflex
        </title>
        <link rel="stylesheet" href={%  static 'css/nick/comment.css' %}>
        <link rel="icon" href={% static 'img/nick/logo.png' %} />
        <!--Global light & dark & mobile -->
        <link rel="stylesheet" href="{% static 'css/nick/light/css/global.css' %}">
        <link rel="stylesheet" href="{% static 'css/nick/dark/css/global.css' %}">
        <link rel="stylesheet" href="{% static 'css/nick/mobile/css/global.css' %}">
        <!--End of scss-->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>

        $(document).ready(function(){
            $('.newCom').hide();
        $('select').on('change', function() {
            if (this.value==='new'){
                $('.oldCom').hide();
                $('.newCom').show();
            }else if (this.value==='old'){
                $('.oldCom').show();
                $('.newCom').hide();
            }
        });
        });
    </script>
    </head>
        <body>
            {% for data in msg %}
            <div class="post">
                <label style="font-size: 24px; padding: 10px; color: rgb(0, 0, 0);"><b>{{ data.title }}</b></label>
                <label id='date' style="color: rgb(179, 163, 149);">{{ data.created_at.day }}.{{ data.created_at.month }}.{{ data.created_at.year }}</label>
                <label style="font-size: 10px;color: rgb(179, 163, 149); padding-left: 5px;">UTC:</label>
                <label id='time' style="color: rgb(179, 163, 149);">{{ data.created_at.hour}}:{{ data.created_at.minute }}</label><br><br>
                <a href='{% url 'ed:profile' %}?user={{ data.user }}' style="float: none; padding: 10px;">{{  data.user }}</a>
                <span>{{ data.message }}</span><br>
                 <label style="float: right; color: rgb(179, 163, 149); margin-top: 10px;">{{ data.dislike.all.count }}</label>
                {% if request.user in data.like.all %}
                    <button id="lb" ><img class="icon" id='dislike' alt="dislike" src={% static 'img/nick/dislike.png' %}  ></button>
                {% else %}
                    {% if request.user in data.dislike.all %}
                        <form action="{% url 'ed:comment' %}?user={{ data.user }}&title={{ data.title }}" method="POST">
                        {% csrf_token %}
                        <button id="lb" name="undislike" value="undislike"><img class="icon" id='dislike' alt="dislike" type="submit" src={% static 'img/nick/dislike.png' %}  ></button>
                        </form>
                    {% else %}
                        <form action="{% url 'ed:comment' %}?user={{ data.user }}&title={{ data.title }}" method="POST">
                        {% csrf_token %}
                        <button id="lb" name="dislike" value="dislike"><img class="icon" id='dislike' alt="dislike" type="submit" src={% static 'img/nick/dislike.png' %}  ></button>
                        </form>
                    {% endif %}
                {% endif %}
                <label style="float: right; color: rgb(179, 163, 149); margin-top: 10px;">{{ data.like.all.count }}</label>
                {% if request.user in data.dislike.all %}
                    <button id="lb"><img class="icon" id='simplike' alt="like" src={% static 'img/nick/simplike.png' %}></button>
                {% else %}
                    {% if request.user in data.like.all %}
                        <form action="{% url 'ed:comment' %}?user={{ data.user }}&title={{ data.title }}" method="POST">
                        {% csrf_token %}
                        <button id="lb" name="unlike" value="unlike"><img class="icon" id='simplike' alt="like" src={% static 'img/nick/simplike.png' %} ></button>
                        </form>
                    {% else %}
                        <form action="{% url 'ed:comment' %}?user={{ data.user }}&title={{ data.title }}" method="POST">
                        {% csrf_token %}
                        <button id="lb" name="like" value="like"><img class="icon" id='simplike' alt="like" src={% static 'img/nick/simplike.png' %} ></button>
                        </form>
                    {% endif %}
                {% endif %}
                <br><br>
                <hr>
                <form method="POST" action="">
                    {% csrf_token %}
                <div id='enterComment'>
                    <label>Enter your comment:</label><br>
                    {{ form.comments }}<br>
                    <button type="submit" style="float: right;">Submit</button><br>
                </div>
                </form>
            </div>
            {% endfor %}
			{% if comments_old %}
				<div id='filter'>
                <select id='sortList'>
                    <option id='old' value="old">Old</option>
                    <option id= 'new' value="new">New</option>
                </select>
                    <label style="float: right; margin-right: 10px;">Sort by:</label>
            </div>
            <div class='oldCom'>
			{% endif %}



            {% for comment in comments_old %}
            <div id='comment'>
                <a href='{% url 'ed:profile' %}?user={{ comment.User }}' style=" float: left;margin-left:10px;">{{ comment.User }}</a><br>
                <span>{{ comment.comments }}</span>
            </div>
{% endfor %}
            </div>
            <div class='newCom'>
            {% for comment in comments_new %}
            <div id='comment'>
                <a href='{% url 'ed:profile' %}?user={{ comment.User }}' style=" float: left;margin-left:10px;">{{ comment.User }}</a><br>
                <span>{{ comment.comments }}</span>
            </div>
            {% endfor %}
            </div>
        </body>
</html>

templates/nick/forum/forum.html
<!DOCTYPE html>
{% load static %}
{% load hashtag %}
<html lang="en">
    <head>
        <title>
            EDgermanflex
        </title>
        <!-- Global Light & Dark -->
        <link rel="stylesheet" href={% static "css/nick/light/css/global.css" %}>
        <link rel="stylesheet" href={% static 'css/nick/dark/css/global.css' %}>
        <link rel="stylesheet" href={% static 'css/nick/mobile/css/global.css' %}>
        <!-- Top-Banner Light & Dark-->
        <link rel="stylesheet" href={% static 'css/nick/light/css/top-banner.scss' %}>
        <link rel="stylesheet" href={% static 'css/nick/dark/css/top-banner.css' %}>
        <!-- Searchbar Light & Dark -->
        <link rel="stylesheet" href={% static 'css/nick/light/css/searchbar.css' %}>
        <link rel="stylesheet" href={% static 'css/nick/dark/css/searchbar.css' %}>
        <!-- Create Post Light & Dark -->
        <link rel="stylesheet" href={% static 'css/nick/light/css/create-post.css' %}>
        <link rel="stylesheet" href={% static 'css/nick/dark/css/create-post.css' %}>
        <!-- Icon -->
        <link rel="icon" href={% static "img/nick/logo.png" %}>

        <meta name="viewport" content="width=device-width">
        <!-- JS -->
        <script src={% static 'js/filterSearch.js' %}></script>
        <script src={% static 'js/newPostUsers.js' %}></script>
        <script src={% static 'js/ddMenu.js' %}></script>
    </head>
    <!--Hardcore starts from here-->
    <body>
    {% include 'nick/top-banner.html' %}
    <!--here new stuff going on-->
    <form action="{% url 'ed:searchworker' %}" method="get">
        <div id="search">
            <input  type="search" name="user" id="searchBar" placeholder="Username">
            <input type="search" name="title" id="searchBar" placeholder="Title">
            <button id="searchButton"><img src="{% static 'img/nick/search.png' %}" style="width: 25px; height: 25px;" alt=""></button>
            <div id='filter' onclick='filterSearch()'><img src="{% static 'img/nick/3dots.png' %}" style="width: 40px; height: 40px;" alt=""></div>


            <div id="advancedList">
                    <a class='advButton' href="{% url 'ed:advfilter' %}">Advanced</a>
                </div>
        </div>
    </form>
            <!--end of new things-->
            <button onclick="location.href='{% url 'ed:create' %}';" id='buttonNewPost'>Create new post</button>
            {% for data in message %}
                <div class="post" id="{{ data.user }}={{ data.title }}">
                <label style="font-size: 24px; padding: 10px; color: rgb(0,0,0);"><b>{{ data.title }}</b></label>
                <label id='date' style="color: rgb(179, 163, 149);">{{ data.created_at.day }}.{{ data.created_at.month }}.{{ data.created_at.year }}</label>
                <label style="font-size: 10px;color: rgb(179, 163, 149); padding-left: 5px;">UTC:</label>
                <label id='time' style="color: rgb(179, 163, 149);">{{ data.created_at.hour}}:{{ data.created_at.minute }}</label><br><br>
                <a id="notwhite" href='{% url 'ed:profile' %}?user={{ data.user }}' style="float: none; padding: 10px;">{{ data.user }}</a>
                <span>{{ data.message }}</span>
                <span id="tags">Keywords :  {% check data.tags %}</span>
                <div style="padding-right: 20px; padding: 5px;"><a id="notwhite" href="{% url 'ed:comment' %}?user={{ data.user }}&title={{ data.title }}">Comment</a></div>
                <br>
                </div>
            {% endfor %}
    </body>
</html>

templates/nick/forum/forum_create.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>
            EDGermanFlex
        </title>
        <link rel="stylesheet" href={% static 'css/nick/forum_create.css' %}>
        <link rel="icon" href={% static 'img/nick/logo.png' %}>
        <!--Global light & dark & mobile -->
        <link rel="stylesheet" href="{% static 'css/nick/light/css/global.css' %}">
        <link rel="stylesheet" href="{% static 'css/nick/dark/css/global.css' %}">
        <link rel="stylesheet" href="{% static 'css/nick/mobile/css/global.css' %}">
        <!--End of scss-->

    </head>
    <!--Hardcore starts from here-->

    <body>
        <center>
         <!--create post for forum-->
        <form action="{% url 'ed:create' %}" method="post">
         {% if request.user.is_authenticated %}
             {% csrf_token %}
         <div id="createPost">
            <label style="padding-right: 10px; float: left;">Topic: </label>
             <label style="float: right; padding: 5px 10px">Logged in as : {{ request.user.username }}</label><br>
            {{ form.title }}<br><br>
            <label style=" float: left;">Keywords:</label><br>
            {{ form.tags }}<br><br>
            <label style="padding-right: 10px; float: left;">Description: </label><br>
            {{ form.message }}<br><br>
             <button type="submit" style="float: right;">Submit</button><br>
        </div>
        </form>
        {% else %}
             <div id="createPost">
                <label>
                    You need to be logged in &nbsp; &nbsp; <a href="{% url 'team:register' %}">Register</a> or <a href="{% url 'team:login_view' %}">Login</a>
                </label>
             </div>
        {% endif %}
        </center>
    </body>
</html>

templates/nick/forum/message_search.html
<!DOCTYPE html>
{% load hashtag %}
{% load static %}
<html>
    <head>
        <title>
            EDgermanflex / Results
        </title>
        <link rel="stylesheet" href={% static 'css/nick/holy-cascade.css' %}>
		<link rel="icon" href={% static 'img/nick/logo.png' %}>
        <!--Global light & dark & mobile -->
        <link rel="stylesheet" href="{% static 'css/nick/light/css/global.css' %}">
        <link rel="stylesheet" href="{% static 'css/nick/dark/css/global.css' %}">
        <link rel="stylesheet" href="{% static 'css/nick/mobile/css/global.css' %}">
        <!--End of scss-->
        <script>
            let filterClicked = false;

        function filterSearch(){
            let filterList = document.getElementById('advancedList')
            let sortList = document.getElementById('sortList')

            if(filterClicked === false){
                filterList.style.display = 'block'
                sortList.style.display = 'block'
                filterClicked = true
            }else{
                filterList.style.display = 'none'
                sortList.style.display = 'none'
                filterClicked = false
            }

        }

        </script>
    </head>
    <!--Hardcore starts from here-->

    <script>
        //change clicked to profileClicked, more understandable
        let profileClicked = false;

        function ddMenu(){
            let ddcont = document.getElementById('dropdown-content');

            if(profileClicked == false){
                ddcont.style.display = 'block'
                profileClicked = true
            }else{
                ddcont.style.display = 'none'
                profileClicked = false
            }
        }

    </script>
    <body>
        <div id="containor">
            <div id="topBanner">

                <!--u have this-->
			{% if request.user.is_authenticated %}
            <div id="dropdown"  style="float: right; margin-right: 50px;">
                <label onclick="ddMenu()">{{ request.user.username }}</label>
                <div  id="dropdown-content">
                    <a href="{% url 'ed:profile' %}" style="float: left;">Profile</a>
                    <a href="{% url 'ed:logout' %}" style="float: left;">Logout</a>
                </div>
            </div>
			{% else %}
			<div id="dropdown"  style="float: right; margin-right: 70px; margin-top: 20px">
                <label onclick="ddMenu()">New ?</label>
                <div  id="dropdown-content">
                    <a href="{% url 'ed:profile' %}" style="float: left;">Profile</a>
                    <a href="{% url 'ed:register' %}" style="float: left;">Register</a>
                    <a href="{% url 'ed:login_view' %}" style="float: left;">Login</a>
                </div>
            </div>
			{% endif %}
                <div>
                    <label>Welcome to the official EDGermanflex site!</label>
                    <img style="width: 120px; height: 120px; float: left; padding-left: 10px;" src="{% static 'img/nick/logo.png' %}">
                </div>
            </div>



            <div id="scroll">
                <button class="buttonTop" onClick="window.location='{% url 'ed:home' %}';">Home</button>
                <button class="buttonTop" onClick="window.location='{% url 'ed:video' %}';">Videos</button>
                <button class="buttonTop" onClick="window.location='{% url 'ed:forum' %}';">Forum</button>
                <button class="buttonTop" onClick="window.location='{% url 'ed:posts' %}';">Post</button>
                <button class="buttonTop" onClick="window.location='{% url 'ed:contact' %}';">Contact</button>
            </div>
            <form action="{% url 'ed:message_search' %}" method="get">
            <div id="search">
                <input type="search" name="searching" id="searchBar" placeholder="Quick Search">
                <button id="searchButton"><img style="width: 25px; height: 25px;" src={% static 'img/nick/search.png' %} > </button>
                <div id='filter' onclick='filterSearch()'><img  style="width: 40px; height: 40px;" src={% static 'img/nick/3dots.png' %}></div>
                <div id="filterNewOld">
                    <select name="Sort by" id='sortList'>
                        <option value="new">New</option>
                        <option value="old">Old</option>
                    </select>
                </div>
               <div id="advancedList">
                    <a class='advButton' href="{% url 'ed:advfilter' %}">Advanced</a>
                </div>
            </div>
            </form>

            {% if search %}
			{% for data in search %}
                <div class="post">
                <label style="font-size: 24px; padding: 10px; color: rgb(0, 0, 0);"><b>{{ data.title }}</b></label><br><br>
                <a id="notwhite" href='{% url 'team:profile' %}?user={{ data.user }}' style="float: none; padding: 10px;">{{ data.user }}</a>
                <span>{{ data.message }}</span>
                <span id="tags">Keywords : {% check data.tags %}</span>
                <a id="notwhite" href="{% url 'ed:comment' %}?user={{ data.user }}&title={{ data.title }}">Comment</a>
                </div>
            {% endfor %}
            {% else %}
                <div class="post">
                <label style="font-size: 24px; padding: 10px; color: rgb(0, 0, 0);"><b>ERROR 404</b></label><br><br>
                <a id="notwhite" href='{% url 'team:profile' %}/?user=-System-' style="float: none; padding: 10px;">-System-</a>
                <span>We searched and searched but we couldn't find for what you where looking.<br>Search for anything else or go Back</span>
                <div style="padding-right: 20px; padding: 10px;"><a id="notwhite" >Don't try it</a></div>
                </div>
            {% endif %}

        </div>
    </body>
</html>