django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ed.urls')),
    path('accounts/', include('allauth.urls')),
]

ed/urls.py
from . import views
from django.urls import path

app_name = 'ed'
urlpatterns = [
    path('', views.home, name='home'),
    path('videos/', views.videos, name='video'),
    # Forum
    path('forum/', views.forum_view, name='forum'),
    path('forum/comment/', views.comment_view, name='comment'),
    path('forum/create', views.forum_create, name='create'),
    path('forum/search/', views.search_post, name='message_search'),
    path('forum/filter', views.advfilter, name='advfilter'),
    path('forum/searchworker/', views.searchworker_view, name='searchworker'),
    # Forum End
    path('posts/', views.posts, name='posts'),
    path('contact/', views.contacts, name='contact'),
    # Prole
    path('profile/', views.profile_view, name='profile'),
    path('profile/fa/', views.fa, name='fa'),
    path('profileadd', views.profile_add, name='profile_add'),
    path('notification', views.notification_view, name='notification'),
    path('settings', views.settings_view, name='settings'),
    # Account
    path('login/', views.login_view, name='login_view'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    # Old Site
    path('sale/', views.sale, name='sale'),
    # For Supporter
    path('supporter/', views.supporter, name='supporter'),
    # Help
    path('problems', views.problems, name='problem'),
    # Rickroll
    path('tests', views.rickroll, name='rickroll'),

]

templates/nick/contacts.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>
            EDGermanFlex / Contacts
        </title>
        <link rel="stylesheet" href={% static 'css/nick/contacts.css' %}>
		<link rel="icon" href={% static 'img/nick/logo.png' %} />
        <!--Global light & dark & mobile -->
        <link rel="stylesheet" href="{% static 'css/nick/light/css/global.css' %}">
        <link rel="stylesheet" href="{% static 'css/nick/dark/css/global.css' %}">
        <link rel="stylesheet" href="{% static 'css/nick/mobile/css/global.css' %}">
        <!--End of scss-->

        <script src={% static 'js/ddMenu.js' %}></script>
    </head>
    <!--Hardcore starts from here-->
    <body>
            {% include 'nick/top-banner.html' %}
                <div class="post">
                    <label style="font-size: 24px; padding: 10px; color:rgb(23,140,148);"><b>How to Contact me  /  Sozial Media</b></label><br>
                    <span>Click on the Name to open the link :
                        <li style="padding-top: 3px"><a class='conlink' href="https://discord.gg/BGtnx2b">Discord</a></li>
                        <li style="padding-top: 3px"><a class="conlink" href="https://www.youtube.com/channel/UC4XnMk-zqFX2KDXNR0Skumw">Youtube</a></li>
                        <li style="padding-top: 3px"><a class="conlink" href="https://twitter.com/nick56245406?s=09">Twitter</a></li>
                    </span>
                </div>
                <div class="post">
                    <label style="font-size: 24px; padding: 10px; color: rgb(23, 140, 148);"><b>Where do I live</b></label><br>
                    <span>Nick is living somewhere </span>
                </div>
                <div class="post">
                    <label style="font-size: 24px; padding: 10px; color: rgb(23, 140, 148);"><b>Found Any Bugs or having Problems ?</b></label><br>
                    <span style="padding-left: 20px">Here are some options
                        <li style="padding-top: 3px">Make Screeshots and send it in the Discord Server Support</li>
                        <li style="padding-top: 3px"><a href="{% url 'ed:problem' %}">Use the Site support by clicking on this</a></li>
                    </span>
                </div>
    </body>
</html>

templates/nick/main_page.html
<!DOCTYPE html>
<html lang="deu">
<head>
    <meta charset="UTF-8">
    <title>EDGermanFlexChannel</title>
    <link rel="icon" href="head.png" />
        <style>
            .Info {
                hspace:"50"
                }

                .heart {
                        fill: red;
                        position: relative;
                        top: 5px;
                        width: 50px;
                        animation: pulse 1s ease infinite;
                        }

                @keyframes pulse {
                        0% { transform: scale(1); }
                        50% { transform: scale(1.3); }
                        100% { transform: scale(1); }
                        }
        </style>
</head>
<body bgcolor="#2d2d2d">



    <svg class="heart" viewBox="0 0 32 29.6">
    <path d="M23.6,0c-3.4,0-6.3,2.7-7.6,5.6C14.7,2.7,11.8,0,8.4,0C3.8,0,0,3.8,0,8.4c0,9.4,9.5,11.9,16,21.2
	c6.1-9.3,16-12.1,16-21.2C32,3.8,28.2,0,23.6,0z"></path>
    </svg>



    <center>
        <img src="../../Website/gems.png" width="=80" height="80" vspace="20" class="gems">
    <b>
        <font size="6" color="#00e5d4">          EDGermanFlexChannel           </font>
    </b>
        <img src="Website/pb.png" width="150" height="150" hspace="40" vspace="0" class="PB" alt="">
    </center>
    <br/><br/>
    <p class="Info">
        <font face="Extra Bold" color="white" size="5">Some Infos</font>
        <img scr="C:\DevCake\Codes\Python\Website\korvapuusti.gif" width="50" height="50">
    <br/>
        <font color="white" face="Bradley Hand ITC">Let me tell you more about what I sell!
            First of all, it can get you special offers on video games! For example, features are sold in a store for a surprisingly low price. DON'T WORRY!!! The Super Nick 13000 will get it for you!!!
            Still not convinced? Alright, here's more it can do! You want to know things about characters in a video game? Just ask! The Super Nick 13000 will make a bunch of videos just for you, and with special shout-outs!!! What could be better?
            Oh, you don't see the point of having two? Okay! The Super Nick 13000 as well as the Special Roninck can make very nice jokes. SO, having two would mean making TWICE MORE JOKES! Amazing, isn't it???
            So what are you waiting for? Just buy it already!!! It's 15000 euros only for each! "Deutsch Qualität" is obviously worth it! And if you buy the two of them, you'll get a special offer: 50% off for the second Nick! So hurry up!!! It's available until tomorrow Tuesday 18th August 23:59!!!</font>
    </p>
    <br/><br/><br/><br/>
    <p>
        <font color="White" size="5">Ein Bischen Werbung</font>
    </p>
    <p align="right">
        <font color="White" size="5" >About the Website</font>
    </p>
    <span style="font-size: medium; ">
    <a href="https://discord.gg/BGtnx2b">Discord Invite für EDGermanFlexChannel</a>
    &nbsp; &nbsp;
    <a href="https://www.youtube.com/channel/UC4XnMk-zqFX2KDXNR0Skumw">Youtube Channel</a>
    </span>
    <br/><br/>
    <button
            onclick="window.location.href='https://whathaveisay.netlify.app';">Don't Click
    </button>
</body>
</html>

templates/nick/nick.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <title>
            EDGermanFlex
        </title>
        <!-- Global light & Dark | Mobile -->
        <link rel="stylesheet" href={% static "css/nick/light/css/global.css" %}>
        <link rel="stylesheet" href={% static 'css/nick/dark/css/global.css' %}>
        <link rel="stylesheet" href={% static 'css/nick/mobile/css/global.css' %}>
        <!-- Top-Banner Light & Dark-->
        <link rel="stylesheet" href={% static 'css/nick/light/css/top-banner.css' %}>
        <link rel="stylesheet" href={% static 'css/nick/dark/css/top-banner.css' %}>
        <!-- Searchbar Light & Dark -->
        <link rel="stylesheet" href={% static 'css/nick/light/css/searchbar.css' %}>
        <link rel="stylesheet" href={% static 'css/nick/dark/css/searchbar.css' %}>
        <!-- Create Post Light & Dark -->
        <link rel="stylesheet" href={% static 'css/nick/light/css/create-post.css' %}>
        <link rel="stylesheet" href={% static 'css/nick/dark/css/create-post.css' %}>
        <!-- Top-Banner Light & Dark | Mobile -->

        <!-- Icon -->
        <link rel="icon" href={% static "/img/nick/logo.png" %} />
        <!-- Meta data -->
        <meta name="viewport" content="width=device-width"/>
        <meta name="theme-color" content="#4285f4"/>
        <meta name="description" content="This is the official Site for EDGermanFlex about Elemental Dungeon">
        <!-- JS -->
        <script src={% static 'js/ddMenu.js' %}></script>
    </head>
    <!--Hardcore starts from here-->
   <body>
   <!-- Top-Banner HTML-->
   {% include 'nick/top-banner.html' %}

   <!-- Post / Some Information in Main Page -->
   <div class="post">
       <label style="font-size: 24px; padding: 10px; color:rgb(23, 140, 148);"><b>About Developers</b></label><br>
       <span class="thx" >Huge thanks goes to
           <li>Resty - for Creating the Site</li>
           <li>Resty - for helping with site and coding cool stuff</li>
           <li>Resty - for Keeping the Site Alive</li>
       </span>
   </div>

   <div class="post">
       <label style="font-size: 24px; padding: 10px; color:rgb(23, 140, 148);"><b>Important</b></label><br>
       <span class="thx">The Original ED is now Dead and not playable anymore.
	   	<li>An unofficial Version, the EDServer2 was made </li>
		<li>It was made by the Person siva1danil#5255 *Discord#tag*</li>
		<li>File is Downloadable in the Discord Server</li>
		<li>Help is also on the Discord Server</li>
		<li>https://discord.gg/KsnJTcQC</li>
		</span>
	   </div>

   <div class="post">
       <label style="font-size: 24px; padding: 10px; color: rgb(23, 140, 148);"><b>General</b></label><br>
       <span>This Site was made for the Community of EDGF (Youtuber Nick)</span>
   </div>
   <!-- Information Ends Here -->
   </body>
</html>

templates/nick/posts.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>
            EDGermanFlex
        </title>
        <link rel="stylesheet" href={% static 'css/nick/nick.css' %}>
		<link rel="icon" href={% static 'img/nick/logo.png' %} />
        <!--Global light & dark & mobile -->
        <link rel="stylesheet" href="{% static 'css/nick/light/css/global.css' %}">
        <link rel="stylesheet" href="{% static 'css/nick/dark/css/global.css' %}">
        <link rel="stylesheet" href="{% static 'css/nick/mobile/css/global.css' %}">
		 <!-- Top-Banner Light & Dark-->
        <link rel="stylesheet" href={% static 'css/nick/light/css/top-banner.css' %}>
        <link rel="stylesheet" href={% static 'css/nick/dark/css/top-banner.css' %}>
        <!--End of scss-->

        <script src={% static 'js/ddMenu.js' %}></script>
    </head>
    <!--Hardcore starts from here-->
    <body>
    {% include 'nick/top-banner.html' %}
            <div class="main">
                <form action="{% url 'ed:searchworker' %}" method="get">
                <div id="search">
                    <input type="search" name="User" id="searchBar" placeholder="Quick Search">
                    <button type="submit" id="searchButton"><img  style="width: 25px; height: 25px;" src="{% static 'img/nick/search.png' %}"></button>
                </div>
            </form>
                <div class="post">
                    <label style="font-size: 24px; padding: 10px; color:rgb(23, 140, 148);"><b></b></label><br>
                        <span>
                            Nothing was posted here
                        </span>
                </div>
            </div>
    </body>

templates/nick/problems.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>
            EDGermanFlex / problems
        </title>
        <link rel="stylesheet" href={% static 'css/nick/forum_create.css' %}>
        <link rel="icon" href={% static 'img/nick/logo.png' %}>
        <!--Global light & dark & mobile -->
        <link rel="stylesheet" href="{% static 'css/nick/light/css/global.css' %}">
        <link rel="stylesheet" href="{% static 'css/nick/dark/css/global.css' %}">
        <link rel="stylesheet" href="{% static 'css/nick/mobile/css/global.css' %}">
        <!--End of scss-->
    </head>
    <!--Hardcore starts from here-->

    <body>
        <center>
         <!--create post for forum-->
        <form action="/team/nick/forum/create" method="post">
         {% if request.user.is_authenticated %}
             {% csrf_token %}
         <div id="createPost">
            <label style="padding-right: 10px; float: left;">Topic: </label>
            <label style="float: right; padding: 5px 10px">Logged in as : {{ request.user.username }}</label><br><br>
            <input type="text" style="float: left"><br><br>
            <label style=" float: left;">Keywords:</label><br>
            <input type="text" style="float: left"><br><br>
            <label style="padding-right: 10px; float: left;">Description: </label><br>
             <textarea type="text" style="float: left"></textarea><br><br>
             <button type="submit" style="float: right;">Submit</button><br>
        </div>
        </form>
        {% else %}
             <div id="createPost">
                <label>
                    You need to be logged in &nbsp; &nbsp; <a href="/team/nick/register">Register</a> or <a href="/team/nick/login">Login</a>
                </label>
             </div>
        {% endif %}
        </center>
    </body>
</html>

templates/nick/supporter.html
static<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <title>
            EDGermanFlex
        </title>
        <link rel="stylesheet" href={% static 'css/nick/nick.css' %}>
		<link rel="icon" href={% static 'img/nick/logo.png' %} />
        <!--Global light & dark & mobile -->
        <link rel="stylesheet" href="{% static 'css/nick/light/css/global.css' %}">
        <link rel="stylesheet" href="{% static 'css/nick/dark/css/global.css' %}">
        <link rel="stylesheet" href="{% static 'css/nick/mobile/css/global.css' %}">
        <!--End of scss-->
        <meta name="viewport" content="width=device-width">
        <!-- JS -->
        <script src="{% static 'js/ddMenu.js' %}"></script>
    </head>
    <!--Hardcore starts from here-->
    <body>
        <div id="containor">
            <div id="topBanner">
                <div>
                    <img class="logo" src={% static 'img/nick/logo.png' %} >
                    <label class="welcome" >Welcome to the official EDGermanflex site!</label>
                    {% if request.user.is_authenticated %}
                    <div id="dropdown"  style="float: right; margin-right: 70px; margin-top: 20px">
                        <label onclick="ddMenu()">{{ request.user.username }}</label>
                            <div  id="dropdown-content">
                                <a href="/team/nick/myaccount" style="float: left;">Profile</a>
                                <a href="/team/nick/logout" style="float: left;">Logout</a>
                            </div>
                    </div>
                    {% else %}
                        <div id="dropdown"  style="float: right; margin-right: 70px; margin-top: 20px">
                        <label onclick="ddMenu()">New ?</label>
                            <div  id="dropdown-content">
                                <a href="/team/nick/myaccount" style="float: left;">Profile</a>
                                <a href="/team/nick/register" style="float: left;">Register</a>
                                <a href="/team/nick/login" style="float: left;">Login</a>
                            </div>
                    </div>
                    {% endif %}
                </div>
            </div>
            <div id="scroll">
                <button class="buttonTop" onClick="window.location='/team/nick/';">Home</button>
                <button class="buttonTop" onClick="window.location='/team/nick/videos';">Videos</button>
                <button class="buttonTop" onClick="window.location='/team/nick/forum';">Forum</button>
                <button class="buttonTop" onClick="window.location='/team/nick/posts';">Post</button>
                <button class="buttonTop" onClick="window.location='/team/nick/contact';">Contact</button>
            </div>
            <div class="main">
                <form action="/team/nick/forum/search" method="get">
                <div id="search">
                    <input type="search" name="User" id="searchBar" placeholder="Quick Search">
                    <button type="submit" id="searchButton"><img src="{% static 'img/nick/search.png' %}" style="width: 25px; height: 25px;"></button>
                </div>
            </form>>
                <div class="post">
                    <label style="font-size: 24px; padding: 10px; color:rgb(23, 140, 148);"><b>smth</b></label><br>
                    <span class="thx" >You need to be Logged in</span>
                <div class="post">
                    <label style="font-size: 24px; padding: 10px; color:rgb(23, 140, 148);"><b>smth</b></label><br>
                    <span>Only Supporter</span>
                </div>
                <div class="post">
                    <label style="font-size: 24px; padding: 10px; color: rgb(23, 140, 148);"><b>smth</b></label><br>
                    <span>Supporter Only</span>
                </div>
            </div>
        </div>
        </div>
    </body>
</html>

templates/nick/top-banner.html
{% load static %}
<div id="topBanner">
    <div>
        {% if request.user.is_authenticated %}
            <div id="dropdown"  style="float: right; margin-right: 70px; margin-top: 20px">
                <label onclick="ddMenu()">{{ request.user.username }}</label>
                <div  id="dropdown-content">
                    <a href="{% url 'ed:profile' %}?user={{ request.user.username }}" style="float: left;">Profile</a>
                    <a href="{% url 'ed:notification' %}" style="float: left;">Notification</a>
                    <a href="{% url 'ed:settings' %}" style="float: left;">Settings</a>
                    <a href="{% url 'ed:logout' %}" style="float: left;">Logout</a>
                </div>
            </div>
        {% else %}
            <div id="dropdown"  style="float: right; margin-right: 70px; margin-top: 20px">
                <label onclick="ddMenu()">New ?</label>
                <div  id="dropdown-content">
                    <a href="{% url 'ed:register' %}" style="float: left;">Register</a>
                    <a href="{% url 'ed:logout' %}" style="float: left;">Login</a>
                </div>
            </div>
        {% endif %}
    </div>
</div>
<!-- Buttons for Top-Banner -->
<div id="scroll">
    <button class="buttonTop" onClick="window.location='{% url 'ed:home' %}';">Home</button>
    <button class="buttonTop" onClick="window.location='{% url 'ed:video' %}';">Videos</button>
    <button class="buttonTop" onClick="window.location='{% url 'ed:forum' %}';">Forum</button>
    <button class="buttonTop" onClick="window.location='{% url 'ed:posts' %}';">Post</button>
    <button class="buttonTop" onClick="window.location='{% url 'ed:contact' %}';">Contact</button>
</div>
<!-- End for Buttons -->

templates/nick/videos.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <title>
            EDGermanFlex
        </title>
        <!-- Global Light & Dark & Mobile-->
        <link rel="stylesheet" href={% static 'css/nick/light/css/global.css' %}>
        <link rel="stylesheet" href={% static 'css/nick/dark/css/global.css' %}>
        <link rel="stylesheet" href={% static 'css/nick/mobile/css/global.css' %}>
        <!-- Videos Light & Dark-->
        <link rel="stylesheet" href={% static 'css/nick/light/css/video.css' %}>
        <link rel="stylesheet" href={% static 'css/nick/dark/css/video.css' %}>
        <!-- Top-Banner Light & Dark -->
        <link rel="stylesheet" href={% static 'css/nick/light/css/top-banner.css' %}>
        <link rel="stylesheet" href={% static 'css/nick/dark/css/top-banner.css' %}>
        <!-- Icon -->
		<link rel="icon" href={% static 'img/nick/logo.png' %} />

        <meta name="viewport" content="width=device-width">
        <!-- JS -->
        <script src={%  static 'js/ddMenu.js' %}></script>
    </head>
    <!--Hardcore starts from here-->
    <body>
    {% include 'nick/top-banner.html' %}

    <div class="main">
        <div class="post">
            <label style="font-size: 24px; padding: 3px; color:rgb(23, 140, 148);"><b>Most  Viewed  Video</b></label><br>
            <span>
                <hr>
                <div class="video-scroll">
                    <iframe class='video' src="https://www.youtube.com/embed/W2MXIjjDJxA" frameborder="0" allow="accelerometer; picture-in-picture" allowfullscreen></iframe>
                    <iframe class="video" src="https://www.youtube.com/embed/RAL-EUMcDU8" frameborder="0" allow="accelerometer; picture-in-picture" allowfullscreen></iframe>
                </div>
            </span>
        </div>
        <div class="post">
            <label style="font-size: 24px; padding: 10px; color:rgb(23, 140, 148);"><b>Character</b></label><br>
            <span>
                <hr>
                <div class="video-scroll">
                    <iframe class="video" src="https://www.youtube.com/embed/W2MXIjjDJxA" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <iframe class="video" src="https://www.youtube.com/embed/UiCoMNXEwkQ" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <iframe class="video" src="https://www.youtube.com/embed/RAL-EUMcDU8" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
            </span>
        </div>
        <div class="post">
            <label style="font-size: 24px; padding: 10px; color: rgb(23, 140, 148);"><b>Boss Guide</b></label><br>
            <span>
                <hr>
                <div class="video-scroll">
                    <iframe class="video" src="https://www.youtube.com/embed/qw7USpop87I" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <iframe class="video" src="https://www.youtube.com/embed/HWLhcvj7eb4" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <iframe class="video" src="https://www.youtube.com/embed/DWyRLVjNxBY" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <iframe class="video" src="https://www.youtube.com/embed/JUvmfMyLGxc" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
            </span>
        </div>
        <div class="post">
            <label style="font-size: 24px; padding: 10px; color: rgb(23, 140, 148);"><b>Tip and Tricks</b></label><br>
            <span>
                <hr>
                <div class="video-scroll">
                    <iframe class="video" src="https://www.youtube.com/embed/AY8zYMIRJQk" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <iframe class="video" src="https://www.youtube.com/embed/ExZk8XE2734" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <iframe class="video" src="https://www.youtube.com/embed/7Wn7kUqPld0" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
            </span>
        </div>
        <div class="post">
            <label style="font-size: 24px; padding: 10px; color: rgb(23, 140, 148);"><b>Damage.mp4</b></label><br>
            <span>
                <hr>
                <div class="video-scroll">
                    <iframe class="video" src="https://www.youtube.com/embed/xTQ1VygFLtM" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <iframe class="video" src="https://www.youtube.com/embed/_-IMRDcDf4k" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <iframe class="video" src="https://www.youtube.com/embed/7c-GOcR3bAk" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
            </span>
        </div>
    </div>
    </body>
</html>